allwinbitcoin/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('', include('core.urls')),
    path('', include('chat.urls')),

    # paths de auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('chat/', views.index, name='index'),
    path('chat/<room_name>/', views.room, name='room'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('home/activar_clon/<int:clon_id>/', views.activar_clon, name='activar_clon'),
    path('home/activar_clon/', views.activar_clon, name='activar_clon'),
    path('ajax/lista_content/', views.lista_content, name='lista_content'),
    path('ajax/lista_content/<int:id_lista>/', views.lista_content,
         name='lista_content'),

    path('ajax/listas/', views.listas, name='listas'),
    path('ajax/clones/', views.clones, name='clones')
]

registration/urls.py
from django.urls import path
from . import views
from .views import RegistroUsuario, login, logged_out, registro_referido

app_name = 'registration'

urlpatterns = [
    path('registro/', RegistroUsuario.as_view(), name='registro'),
    path('registro/<patrocinador>/', views.registro_referido,
         name='registro_referido'),
    path('login/', login.as_view(), name='login'),
    path('logged_out/', logged_out.as_view(), name='logged_out'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User


class Lista(models.Model):
    TIPO_CHOICES = (
        ('P', 'Principal'),
        ('S1', 'Sublista Izq'),
        ('S2', 'Sublista Ciclaje'),
    )
    ESTADO_CHOICES = (
        ('A', 'ABIERTA'),
        ('C', 'CERRADA'),
        ('B', 'BLOQUEADA')
    )
    alias = models.CharField(default='', max_length=20, blank=True, null=True)
    nivel = models.ForeignKey('Nivel', blank=True, null=True,
                              on_delete=models.CASCADE)
    max_items = models.SmallIntegerField(default=7)
    items = models.SmallIntegerField(default=0)
    cycle_position = models.SmallIntegerField(default=6)
    ciclo = models.BigIntegerField(default=0)
    jugador = models.ManyToManyField('Jugador', default='', blank=True,
                                     through='Juego',
                                     through_fields=('lista', 'jugador'))
    lista_padre = models.ForeignKey('self', on_delete=models.CASCADE,
                                    null=True,
                                    blank=True)
    tipo = models.CharField(max_length=2, choices=TIPO_CHOICES)
    estado = models.CharField(max_length=1, choices=ESTADO_CHOICES,
                              default='A')
    estado_der = models.CharField(max_length=1, choices=ESTADO_CHOICES,
                                  default='A')
    estado_izq = models.CharField(max_length=1, choices=ESTADO_CHOICES,
                                  default='A')
    nivel = models.ForeignKey('Nivel', on_delete=models.CASCADE, default=1)
    pc = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name_plural = 'Listas'
        ordering = ['created']


class Juego(models.Model):
    lista = models.ForeignKey(Lista, on_delete=models.CASCADE)
    jugador = models.ForeignKey('Jugador', on_delete=models.CASCADE)
    posicion = models.SmallIntegerField(default=-1)
    posicion_cerrado = models.SmallIntegerField(default=-1)
    color_cerrado = models.CharField(max_length=10, default='red')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.jugador) + ' jugando en lista ' + str(self.lista)

    class Meta:
        verbose_name_plural = 'Juegos'
        ordering = ['created']


class Jugador(models.Model):
    usuario = models.OneToOneField(User,
                                   on_delete=models.CASCADE)
    n_referidos = models.SmallIntegerField(default=0)
    n_referidos_activados = models.SmallIntegerField(default=0)
    color = models.CharField(max_length=10, default='red')
    ciclo = models.BigIntegerField(default=0)
    patrocinador = models.ForeignKey('self', blank=True, null=True,
                                     on_delete=models.CASCADE)
    whatsapp = models.CharField(max_length=10, blank=True, null=True)
    celular = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return str(self.usuario)

    class Meta:
        verbose_name_plural = 'Jugadores'


class Nivel(models.Model):
    indice = models.SmallIntegerField(default=1, unique=True, blank=True)
    monto = models.DecimalField(max_digits=10, decimal_places=2, default=50000)

    def __str__(self):
        return "Nivel " + str(self.monto)

    class Meta:
        verbose_name_plural = 'Niveles'


class Clon(models.Model):
    ESTADO_CHOICES = (
        ('P', 'PENDIENTE ACTIVAR'),
        ('A', 'ACTIVO'),
    )
    jugador = models.ForeignKey('jugador', blank=True, null=True,
                                on_delete=models.CASCADE)
    estado = models.CharField(max_length=1, choices=ESTADO_CHOICES,
                              default='P')
    nivel = models.ForeignKey('Nivel', on_delete=models.CASCADE, default=1)

    def __str__(self):
        return 'clon de ' + str(self.jugador)

    class Meta:
        verbose_name_plural = 'Clones'

core/views.py
import datetime
import json
from django.views.decorators.csrf import requires_csrf_token
from django.utils import timezone
from django.db.models import F
from django.db import transaction
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.http import HttpResponse
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from .models import Lista, Jugador, Juego, Clon

def index(request):
    return render(request, 'core/index.html')


@login_required
@requires_csrf_token
def home(request, id_usuario=None, id_lista=None):
    hora_local = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return render(request, 'core/home.html', {
        'hora_local': hora_local,
        'base_url': request.build_absolute_uri('/')[:-1].strip("/")})


@receiver(post_save, sender=Jugador)
def activar_jugador(instance, created, **kwargs):
    if created:
        asignar_jugador(instance)


@transaction.atomic
def asignar_jugador(nuevo_jugador):
    log_registrar('log.txt', 'NUEVO JUGADOR Patrocinador ' +
                  str(nuevo_jugador.patrocinador) + ' Jugador: ' +
                  str(nuevo_jugador))

    # buscar lista y posición valida del patrocinador
    nueva_ubicacion = {'lista': None,
                       'posicion': -1,
                       'patrocinador': None}

    nueva_ubicacion = buscar_ubicacion(nuevo_jugador.patrocinador)

    if nueva_ubicacion['posicion'] != -1:
        # Creamos el juego para enlazar la lista con el nuevo jugador
        juego = Juego(lista=nueva_ubicacion['lista'],
                      jugador=nuevo_jugador,
                      posicion=nueva_ubicacion['posicion'])
        juego.save()
        juego.refresh_from_db()
        log_registrar('log.txt', 'Jugador ' + str(nuevo_jugador) +
                      ' agregado a lista ' + str(nueva_ubicacion['lista']) +
                      ' en posicion: ' +
                      str(nueva_ubicacion['posicion']))

        # procesos post asignacion directa
        lista_inc_item(nueva_ubicacion['lista'])

        jugador_validar_bloqueos(nuevo_jugador.patrocinador)
        jugador_validar_pcs(nuevo_jugador.patrocinador)
        jugador_inc_referidos(nuevo_jugador.patrocinador)
        jugador_inc_activos_abuelo(nuevo_jugador.patrocinador, nueva_ubicacion['lista'].nivel)
        respuesta = 'Jugador asignado correctamente'
        notificar_asignacion()

        # Creacion de lista izquierda
        if nueva_ubicacion['posicion'] == 4:
            # aquí debo cerrar la lista izquierda
            lista_cerrar_izq(nueva_ubicacion['lista'])
            lista_nueva_izq(nueva_ubicacion['lista'])

        # bloque de ciclaje de jugadores
        elif nueva_ubicacion['posicion'] == 5:
            #ciclo la lista en la nueva ubicacion
            ret_ciclado = lista_ciclar(nueva_ubicacion['lista'])
            if ret_ciclado['posicion'] == 4:
                # aquí debo cerrar la lista izquierda
                lista_cerrar_izq(ret_ciclado['lista'])
                lista_nueva_izq(ret_ciclado['lista'])
            elif ret_ciclado['posicion'] == 6:
                # aquí debo cerrar la lista derecha
                lista_cerrar_der(ret_ciclado['lista'])
                lista_nueva_der(ret_ciclado['lista'])
            #bloque de multiples asignaciones en posición de ciclaje
            while ret_ciclado['posicion'] == 5:
                ret_ciclado = lista_ciclar(ret_ciclado['lista'])
                if ret_ciclado['posicion'] == 4:
                    # aquí debo cerrar la lista izquierda
                    lista_cerrar_izq(ret_ciclado['lista'])
                    lista_nueva_izq(ret_ciclado['lista'])
                elif ret_ciclado['posicion'] == 6:
                    # aquí debo cerrar la lista derecha
                    lista_cerrar_der(ret_ciclado['lista'])
                    lista_nueva_der(ret_ciclado['lista'])

        # Creacion de lista derecha
        elif nueva_ubicacion['posicion'] == 6:
            # aquí debo cerrar la lista derecha
            lista_cerrar_der(nueva_ubicacion['lista'])
            lista_nueva_der(nueva_ubicacion['lista'])

    else:
        respuesta = 'Ocurrio un error al intentar asignar al jugador'
    return respuesta


@transaction.atomic
def asignar_clon(clon):
    log_registrar('log.txt', 'asgnando clon de ' + str(clon.jugador))
    nueva_ubicacion = {'lista': None,
                       'posicion': -1,
                       'patrocinador': None}

    nueva_ubicacion = lista_buscar_mas_antigua()

    if nueva_ubicacion['posicion'] != -1:
        # Creamos el juego para enlazar la lista con el clon
        juego = Juego(lista=nueva_ubicacion['lista'],
                      jugador=clon.jugador,
                      posicion=nueva_ubicacion['posicion'])
        juego.save()
        juego.refresh_from_db()
        log_registrar('log.txt', 'Jugador ' + str(clon.jugador) +
                      ' agregado a lista ' + str(nueva_ubicacion['lista']) +
                      ' en posicion: ' +
                      str(nueva_ubicacion['posicion']))

        lista_inc_item(nueva_ubicacion['lista'])
        notificar_asignacion()


        if nueva_ubicacion['posicion'] == 4:
            # aquí debo cerrar la lista izquierda
            lista_cerrar_izq(nueva_ubicacion['lista'])
            lista_nueva_izq(nueva_ubicacion['lista'])

        elif nueva_ubicacion['posicion'] == 5:
            ret_ciclado = lista_ciclar(nueva_ubicacion['lista'])
            while ret_ciclado['posicion'] == 5:
                ret_ciclado = lista_ciclar(ret_ciclado['lista'])
            if ret_ciclado['posicion'] == 4:
                # aquí debo cerrar la lista izquierda
                lista_cerrar_izq(ret_ciclado['lista'])
                lista_nueva_izq(ret_ciclado['lista'])
            elif ret_ciclado['posicion'] == 6:
                # aquí debo cerrar la lista derecha
                lista_cerrar_der(ret_ciclado['lista'])
                lista_nueva_der(ret_ciclado['lista'])

        elif nueva_ubicacion['posicion'] == 6:
            # aquí debo cerrar la lista derecha
            lista_cerrar_der(nueva_ubicacion['lista'])
            lista_nueva_der(nueva_ubicacion['lista'])
    else:
        pass
        # respuesta = 'Ocurrio un error al intentar asignar el clon'
    return HttpResponse(reverse('core:home'))


def buscar_ubicacion(patrocinador):
    ubicacion = {'lista': None,
                 'posicion': -1,
                 'patrocinador': None}

    # if patrocinador is not None:
    ubicacion = lista_buscar_padre(patrocinador)

    if ubicacion['posicion'] != -1:
        return ubicacion
    else:
        ubicacion = lista_buscar_descendencia(patrocinador)
        if ubicacion['posicion'] != -1:
            return ubicacion
        else:
            ubicacion = lista_buscar_mas_antigua()
            if ubicacion['posicion'] != -1:
                return ubicacion
            else:
                log_registrar('log.txt', 'no hay listas disponibles')
                return ubicacion

# Busquedas de posición sobre las listas
def lista_buscar_padre(patrocinador):
    log_registrar('log.txt', 'Busqueda por padre')
    ubicacion = {'lista': None,
                 'posicion': -1,
                 'patrocinador': None}
    if patrocinador is not None:
        listas_padre_a = Lista.objects\
                              .filter(juego__jugador_id=patrocinador.id)\
                              .filter(estado='A')\
                              .order_by('created')
        if listas_padre_a.exists():
            for lista in listas_padre_a:
                posicion = posicion_nuevo_jugador(patrocinador, lista)
                if posicion != -1:
                    ubicacion['lista'] = lista
                    ubicacion['posicion'] = posicion
                    ubicacion['patrocinador'] = patrocinador
                    break
    return ubicacion


def lista_buscar_descendencia(patrocinador):
    log_registrar('log.txt', 'Busqueda por descendencia')
    ubicacion = {'lista': None,
                 'posicion': -1,
                 'patrocinador': None}

    nueva_ubicacion = {'lista': None,
                       'posicion': -1,
                       'patrocinador': None}

    if patrocinador is not None:
        patrocinador = Jugador.objects.get(pk=patrocinador.id)
        if patrocinador.patrocinador is not None:
            abuelo = Jugador.objects.get(pk=patrocinador.patrocinador.id)
            while abuelo is not None and nueva_ubicacion['posicion'] == -1:
                nueva_ubicacion = lista_buscar_padre(abuelo)
                if nueva_ubicacion['posicion'] != -1:
                    ubicacion['posicion'] = nueva_ubicacion['posicion']
                    ubicacion['lista'] = nueva_ubicacion['lista']
                    ubicacion['patrocinador'] = nueva_ubicacion[
                        'patrocinador']
                else:
                    if abuelo.patrocinador is not None:
                        patrocinador_abuelo = abuelo.patrocinador
                        abuelo = Jugador.objects.get(pk=patrocinador_abuelo.id)
                    else:
                        abuelo = None
    return ubicacion


def lista_buscar_mas_antigua():
    log_registrar('log.txt', 'Busqueda lista más antigua')
    ubicacion = {'lista': None,
                 'posicion': -1,
                 'patrocinador': None}
    listas_abiertas = Lista.objects.filter(estado='A')\
                                   .order_by('created')
    for lista in listas_abiertas:
        # si la lista no tienen items es porque empezamos el juego
        if lista.items == 0:
            ubicacion['lista'] = lista
            ubicacion['posicion'] = 0
            ubicacion['patrocinador'] = None
            return ubicacion
        else:

core/templates/core/base.html
{% load static %}
  <!doctype html>
  <html lang="es">
   <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "core/css/style.css" %}">
    {% block titulo %} {% endblock %}
  </head>
  
  <body>
    <div id="chat-log"></div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark"> <!-- barra de navegación Superior  -->
      <a class="navbar-brand" href="#">Pasamano.com</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
          </li>       
        </ul>
        <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'registration:logged_out' %}">Salir</a></li> 
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container-fluid"> <!-- barra de navegación lateral izquierda y contenido drecha --> 
      <div class="row">
        <div class="col-sm-12 col-md-3 col-lg-3 col-xl-2 ">
          <!--barra lateral de navegacion -->          
          <div class= "nav-simple"> 
            <nav class="nav flex-column">
              <span class= "separator"> MENU </span>
              
              <a class="nav-link active" 
                href="{% url 'core:home'%}"><i class="fas fa-th">
              </i>Home</a>
              <a class="nav-link" href="{% url 'core:home' %}">
                <i class="fas fa-list"></i>Tienda</a>
              <hr>
            </nav>
          </div>
          
          <!-- </nav>/-->
        </div>
        <div class="col-sm-12 col-md-9 col-lg-9 col-xl-10"> <!-- lateral derecho-->
          {% block contenido %} {% endblock %}
        </div>
      </div>  
      
      <div class="row">  <!-- Pie de pagina-->
        <div class="card w-100">
          <div class="card-body">
            <p class="card-text text-center">© 2018 All Win Bitcoin</p>                   
          </div>
        </div>
      </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="{% static "core/js/reloj.js" %}"></script>
    <script src="{% static "core/js/home.js" %}"></script>
    <script type=text/javascript>
    window.onload = function preInit(){
        url_lista_content = "{% url 'core:lista_content' %}";
        url_listas = "{% url 'core:listas' %}";
        url_clones = "{% url 'core:clones' %}";
        url_activar_clon = "{% url 'core:activar_clon' %}";
        init('{{hora_local}}');
      }  
    </script>
  </body>
</html> 

core/templates/core/base_general.html
{% load static %}
  <!doctype html>
  <html lang="es">
   <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "core/css/style.css" %}">

    {% block titulo %} {% endblock %}
  </head>
  <body> 
    {% block contenido %} {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html> 

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}


{% block contenido %}
  <h3> Bienvenido {{ request.user }}</h3>
  
  
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        Este es tu enlace de referido:
        <div class="input-group">
            <input id="txtEnlaceReferido" class="form-control" value="{{base_url}}{% url 'registration:registro_referido' request.user %}" name=""  readonly> 
            <span class= input-group-btn> 
              <button id="btnCopiar" class="btn btn-primary">Copiar</button>
              <button id = "btnWhatsapp">
                <img height="30px" src="{% static "core/img/wa.png" %}" alt="Compartir en whatsapp">  
              </button>              
            </span>
          </div>
      </div>  
    </div>
    
    
    <div class="row">

      <div class="col-md-6">
        <div class="card w-100">
          <h6 class="card-header"> Mis Listas </h6>
          <div class="card-body scroll-list" style="height: 18rem;">
            <p class="card-text">
                <div id ="listasContainer"></div>
            </p>
          </div>
        </div>
      </div>

<!--codigo actual para cargar los jugadores de la lista   -->    

      <div class="col-md-6">
        <div class="card w-100">
          <h6 class="card-header">
            <div id="encabezado_lista">
            Seleccione una lista para ver su contenido
            </div>
          </h6>
          <div class="card-body" style="height: 18rem;">
            <p class="card-text">
              <div id="lista_content">
              
              </div>
              
              <div class="container">
              <!-- Primera fila   -->              
                <div class="row">
                <div class="col-12 text-center">
                  <h5>
                    <div style="border-style: dashed; font-weight: bold;" id="j0"></div>
                  </h5>

                </div>
              </div> 
              <!-- segunda fila   -->              
              <div class="row">
                <div class="col-6">
                  <h6>
                    <div class="text-center" id="j1"></div>
                  </h6>  
                </div>
                <div class="col-6">
                    <h6>
                      <div class="text-center" id="j2"></div>
                    </h6>  
                </div>
              </div> 
              <!-- tercera fila   -->              
              <div class="row">
                <div class="col-3">
                    <h6>
                      <div class="text-center" id="j3"></div>
                    </h6>
                </div>
                <div class="col-3">
                    <h6>
                      <div class="text-center" id="j4"></div>
                    </h6>
                </div>
                <div class="col-3">
                    <h6>
                      <div class="text-center" id="j5"></div>
                    </h6>
                </div>
                <div class="col-3">
                    <h6>
                      <div class="text-center" id="j6"></div>
                    </h6>
                </div>
              </div>
            </div>
          </p>
        </div> 
      </div>
    </div>

    <div class="col-md-6">
      <div class="card w-100">
        <h6 class="card-header"> Mis Clones </h6>
        <div class="card-body scroll-list" style="height: 18rem;">
          <p class="card-text">
            <div id="clonesContainer">
          </div>
          </p>
        </div> 
      </div>
    </div>

    <div class="col-md-6">
      <div class="card w-100">
        <h6 class="card-header"> Reloj y Pagos </h6>
        <div class="card-body scroll-list" style="height: 18rem;">
          <p class="card-text">
            <div id="reloj"></div><br>
            <button type="button" class="btn btn-primary">Pagado</button>
            <button type="button" class="btn btn-primary"> + Tiempo (2 Horas)</button>

          </p>
        </div> 
      </div>
    </div>

  </div>
</div>    
{% endblock %}  

core/templates/core/index.html
{% extends 'core/base_general.html' %}
{% load static %}
{% block contenido %}
  <div class="container-fluid index-background" >
    <div class="row">
      <div class="col-md-5 p-0">
        <div class="card index-card mb-0">
          <img class= "index-logo mx-auto pt-2"  src="{% static "core/img/logo.png" %}" alt="">
          <div class="card-body">
            <br>
            <h6>Generando nuevas alternativas económicas, y oportunidades en redes online.</h6>
            <br>Accede a nuestra plataforma o regístrate para ser socio de nuestro club.
            <div class = "d-flex justify-content-center mt-2 p-2">
              <a href="{% url 'core:home' %}" class="btn btn-success m-2 ">Acceder</a>
              <a href="{% url 'registration:registro'%}" class="btn btn-success m-2 ">Registrarse</a>  
            </div>
          </div>
        </div>
      </div>  
    </div>      
  </div>
{% endblock %}

core/templates/core/registro.html
{% load static %}
{% block contenido %}
<a href="{% url 'core:home' 1 %}">Home</a>
  <div> {{ respuesta }} </div>
  <form action="{% url 'core:registro' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="patrocinador" placeholder="Patrocinador"><br>
    <input type="text" name ="usuario" placeholder="Usuario"><br>
    <input type="text" placeholder="Contraseña"><br>
    <input type="submit" value="Registro">
  </form>
{% endblock %}